spring.application.name=foodgo-api

server.port=8080

# ==============================
# PostgreSQL (produção)
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_foodgo
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==============================
# JPA / Hibernate
# ==============================
# update: cria tabelas se não existirem e atualiza sem apagar dados
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
